version: '3.8'

services:
  web:
    build: .
    container_name: empanada_web
    expose:
      - 5000
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:16
    container_name: empanada_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - empanada_data:/var/lib/postgresql/data
    restart: always

volumes:
  empanada_data: