version: '3.8'

services:
  web:
    build: .
    container_name: empanada_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

