"""Initial migration.

Revision ID: 29039053d1ee
Revises: 
Create Date: 2024-08-04 12:13:04.850126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29039053d1ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('owner_info_user_id_fkey', 'owner_info', type_='foreignkey')
    op.drop_constraint('owner_info_location_id_fkey', 'owner_info', type_='foreignkey')
    op.create_foreign_key(None, 'owner_info', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'owner_info', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner_info', type_='foreignkey')
    op.drop_constraint(None, 'owner_info', type_='foreignkey')
    op.create_foreign_key('owner_info_location_id_fkey', 'owner_info', 'location', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('owner_info_user_id_fkey', 'owner_info', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
